### ISSUE TITLE
Type mismatch error when compiling LNFL

### ISSUE THREAD

**Issue by kslong** [AER-RC/LNFL#10]
I have so far been unble to compile LNFL (and LBRTM) on my mac monterey and on ubuntu because of type mismatch problems.  I am trying to complie with gfortran version 12.3 on my mac and with version 11.3 on ubuntu.  The problem is almost certainly associated with the facty that type mismatch issues are now errors as opposed to warnings as indicated [here](https://www.scivision.dev/gfortran-type-mismatch-error/)

[today.txt](https://github.com/AER-RC/LNFL/files/10127932/today.txt)

**Comment by kslong** [comment]
Note that I can convert the errors to warnings, using the switch indicated in the link above, but then I still end up with a problem, or the form

```
Error: Actual argument contains too few elements for dummy argument 'molcpl' (38/47) at (1)
Error: Actual argument contains too few elements for dummy argument 'molcpl' (38/47) at (1)
```

**Comment by pernak18** [comment]
thanks @kslong

have you tried the solution in https://github.com/AER-RC/LNFL/issues/2#issue-848730176 and #4? basically, LNFL needs to be upgraded to be compatible with newer versions of `gfortran`(if memory serves correctly, > 4.7), but there is a workaround using the `-std=legacy` keyword into the compiler that has worked for others in the community

**Comment by kslong** [comment]
Thank you. With that suggestion I now have the lnfl (and llbrtm) s/w installed on my mac and unbuntu linux box.

From: Rick Pernak ***@***.***>
Reply-To: AER-RC/LNFL ***@***.***>
Date: Thursday, December 1, 2022 at 5:56 AM
To: AER-RC/LNFL ***@***.***>
Cc: Knox Long ***@***.***>, Mention ***@***.***>
Subject: Re: [AER-RC/LNFL] Type mismatch error when compiling LNFL (Issue #10)


thanks @kslong<https://urldefense.com/v3/__https:/github.com/kslong__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!wWs2rGTU4l28dIU4spcUE4Yc8FWQ8aOKII7GYqNXKjJNFo9oWutJQ7wMeJzKTcExbnRBXHS1ZpoJUPkH781THQ$>

have you tried the solution in #2 (comment)<https://urldefense.com/v3/__https:/github.com/AER-RC/LNFL/issues/2*issue-848730176__;Iw!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!wWs2rGTU4l28dIU4spcUE4Yc8FWQ8aOKII7GYqNXKjJNFo9oWutJQ7wMeJzKTcExbnRBXHS1ZpoJUPmzA5MzHA$> and #4<https://urldefense.com/v3/__https:/github.com/AER-RC/LNFL/issues/4__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!wWs2rGTU4l28dIU4spcUE4Yc8FWQ8aOKII7GYqNXKjJNFo9oWutJQ7wMeJzKTcExbnRBXHS1ZpoJUPknD_mvcg$>? basically, LNFL needs to be upgraded to be compatible with newer versions of gfortran(if memory serves correctly, > 4.7), but there is a workaround using the -std=legacy keyword into the compiler that has worked for others in the community
