### ISSUE TITLE
could you provide a couple of example TAPE5 files?

### ISSUE THREAD

**Issue by maroonaggie** [AER-RC/LNFL#11]
Thanks.

**Comment by pernak18** [comment]
@maroonaggie:
```
$ TAPE5 for U of Minnesota VOC RT modeling
   600.000  2600.000
11111111111111111111111111111011111111100000000  LNOUT
```
is one simple example where we grab spectroscopy between 600 and 2600 cm<sup>-1</sup> for all molecules up to CH<sub>3</sub>Br (molecule 40) excluding SF<sub>6</sub> (molecule 30) and produces an ASCII `TAPE7` that contains the same information as the `TAPE3` binary that you will likely use in LBLRTM.

the first line is a comment, the second line is the spectral range, and third line are LNFL options. if you want to adjust, please see the corresponding [section](https://github.com/AER-RC/LNFL#lnfl-tape5-) in our README.

thanks for your interest in LNFL.
