### ISSUE TITLE
GCC8 breaks LNFL

### ISSUE THREAD

**Issue by jonathan-g** [AER-RC/LNFL#2]
Same issue as https://github.com/AER-RC/LBLRTM/issues/9. I'm posting here as a cross-reference in case other people run into errors like 
```
Error: Actual argument contains too few elements for dummy argument ‘molcpl’ (38/47) at (1)
../src/lnfl.f:566:29:

  566 |             CALL CPSTOR_100 (molcpl,npl)
      |                             1
Error: Actual argument contains too few elements for dummy argument ‘molcpl’ (38/47) at (1)
../src/lnfl.f:3817:18:

 3817 |          STR(I) = STR(I)/(VNU(I)*(1.0-EXP(-BETA0*VNU(I))))               LN15580
      |                  1
```

with gfortran under Ubuntu 20.04 and later.

Editing the makefile similarly to the recommendation in https://github.com/AER-RC/LBLRTM/issues/9 solves the problem.

**Comment by pernak18** [comment]
thanks @jonathan-g ! we'll keep this in mind for the next release

**Comment by aayushgambhir21** [comment]
I added "-std=legacy" like the LBLRTM#9 form suggested, but I still get the same error. I am trying to run the lnfl.f file, but I stil get the errors. Can you give me any tips or suggestions to get past this?
