### ISSUE TITLE
does not compile with gfortran 8 

### ISSUE THREAD

**Issue by michaelweber-at** [AER-RC/LNFL#4]
compile fails on linux with a recent fortran compiler. Using the "-std=legacy" option makes the compiler run through.

**Comment by michaelweber-at** [comment]
sorry, I saw this is already addressed in LBLRTM

**Comment by aayushgambhir21** [comment]
Could you show an example? How did you resolve this? I am using a mac laptop, and facing the same error. Or could you point where in the LBLRTM this issue is addressed?

**Comment by pernak18** [comment]
> Could you show an example? How did you resolve this? I am using a mac laptop, and facing the same error. Or could you point where in the LBLRTM this issue is addressed?

@aayushgambhir21 https://github.com/AER-RC/LBLRTM/issues/9 though it looks like it did not help for one mac user. worth a shot, though

**Comment by varisht-tathya** [comment]
Tried compiling with the added flag "-std=legacy" on Kubuntu 20.04. Worked fine for me.
