### ISSUE TITLE
Duplicated lines in aer_v_3.8.1

### ISSUE THREAD

**Issue by asmette** [AER-RC/LNFL#6]
Hi, 

It seems to me there are still duplicated lines in aer_v3.8.1.
Indeed, the linux command 
`uniq -d aer_v_3.8.1 | wc -l `
suggests that the file has ~ 53,000 duplicated lines.

I could obtain a cleaned version using
`mv aer_v_3.8.1 aer_v_3.8.1_orig`
`uniq aer_v_3.8.1_orig > aer_v_3.8.1 `

Or do I miss something?

Best regards, Alain Smette

**Comment by matt-alvarado** [comment]
@kcadyper can you ask Jeana to check on this, looking at the files by molecule? I think we found duplicate lines already in some line file - are we just waiting to push the update?

**Comment by kcadyper** [comment]
I removed the duplicate lines in the O2 file; this change is aer_v_3.8.1; I will ask Jeana to check the other molecules.

**Comment by kcadyper** [comment]
Thanks for finding this issue Alain. We had  found the problem with the O2 lines above 4000 cm-1 while we were running some comparisons with measurements in 4000-15000 cm-1 range, but did not check below 4000 cm-1.  We should have an updated line file soon.
