### ISSUE TITLE
Duplicated H2O lines

### ISSUE THREAD

**Issue by asmette** [AER-RC/LNFL#7]
Hi, 

 It seems there is at least one other case of duplicated lines, affecting H2O. This was forwarded to me by my colleague, Romain Allart.

A first case is:
`1116984.843045 2.010D-24 9.537E-03.0849.3880  325.34790.62-.032000 54  1 6 0 6    5 0 5   3076244 4`
**`1116984.847100 2.074D-24 9.843E-03.0838.3910  325.34790.36-.026200 57  1 6 1 6    5 0 5   3345334 7`**
These 2 lines have very similar parameters. The line in bold is not in HITRAN 2020.

He also reported that the 2nd line of the following 3 is likely wrong. But this does not look like a duplication:
`1115437.809294 2.980D-24 8.061E-03.0948.4340  173.36580.69-.019000 48  1 4 1 3    3 1 2   4672244 7`
`1115437.856300 5.954D-25 7.045E-03.0832.3910  326.62550.62-.024589 48  1 6 1 6    5 1 5   3342034 7`
`1115437.893285 3.311D-26 2.026E-04.0769.4120  382.51690.67-.021191 45  1 5 4 1    4 3 2   2342034 7`

Best regards, 
Alain Smette

**Comment by pernak18** [comment]
see https://github.com/AER-RC/LNFL/issues/6#issuecomment-1202615442
