### ISSUE TITLE
 ASCII line file parameter database (available at RTWeb) is not accessible

### ISSUE THREAD

**Issue by liuxyatgithub** [AER-RC/LNFL#8]
I am learning using your LBLRTM. It needs  the TAPE3 file, which is created by LNFL. To use LNFL,  the ASCII line file parameter database from  RTWeb is needed. But http://rtweb.aer.com/line_param_download.php is not accessible. Can I get the file? By the way, is the TAPE5 included in that datase? Your response will be appreciated. Thank you.

**Comment by pernak18** [comment]
@liuxyatgithub apologies for the late response. a few years ago, we migrated away from our internal web server and made the database publicly available via [Zenodo](https://zenodo.org/record/5120012). have a look at that link and let us know if you have any problems with the package.

you need separate `TAPE5` files for LBLRTM and LNFL -- please see https://github.com/AER-RC/LBLRTM/issues/17#issuecomment-1139557962 and let us know if you need more clarity

thank you!

**Comment by liuxyatgithub** [comment]
Your response helps me to solve the problem. Thank you very much.
